# Generated by Django 2.1.1 on 2018-11-05 22:01

import distributed.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.FileField(upload_to=distributed.models.content_file_name),
        ),
    ]
